### ISSUE TITLE
Tele-op Joystick Turning Drift

### ISSUE THREAD

**Issue by sorrelyn** [oscarrobotics/FTC-2016-OpModes#1]
After pressing the turning joystick (currently left joystick) to turn and letting go, the robot's inertia causes it to turn to an intuitive position and then back to what the target position was actually set to. This also causes issues with fine turning.

**Comment by Bankst** [comment]
I believe the effect was dampened in commit https://github.com/oscarrobotics/FTC-2016-OpModes/commit/4aec40f46956dfbe7db17e038c2818b2a38404b3, and drivers don't seem to mind (or notice) what little effect it still has. Closing.
