### ISSUE TITLE
Shooter not cycling properly

### ISSUE THREAD

**Issue by sorrelyn** [oscarrobotics/FTC-2016-OpModes#2]
Hitting the trigger occasionally causes the shooter to index properly, and sometimes doesn't.

Don't know where that comes from, since we haven't changed any shooter code in the BaseOp.

**Comment by Bankst** [comment]
This has been fixed in https://github.com/oscarrobotics/FTC-2016-OpModes/commit/71f3ccaae9c19d7e0b376db7a073288c8c530081. Re-open this if it comes back up.
